### ISSUE TITLE
New command suggestion: !color

### ISSUE THREAD

**Issue by v1nam** [gurkult/gurkbot#102]
This command can be used a good tool to show pictures of hex colors or rgb, for example if the user invokes through `!color #ff0123` the bot will send a picture of that color

I would like to work on this myself

**Comment by gustavwilliam** [comment]
Yes please! I *really* want this.

Could you also allow both with and without the `#`?

**Comment by v1nam** [comment]
yeah, I am going to make a separate parser function which parses the input and returns a color type
