### ISSUE TITLE
Make GEP channel

### ISSUE THREAD

**Issue by RandomDev26** [gurkult/gurkbot#12]
This command will make a new GEP channel, and also edit channel description.
Usage:

- `!gep make <GEP number> <GEP description>` (makes new channel named `gep-<num>` and sets description as inputted.
- `!gep edit <num> <description>` (edit's the channel's description)

I would like to implement this myself.

**Comment by gustavwilliam** [comment]
I'm not sure we want to let people "make" GEPs that easily. It would probably be better to ask a council member if it's something we want. Maybe a command like this could work:
`!get propose <title> <short summary>`

The actual writing process is a lot larger. Maybe some management commands would be nice though.

**Comment by RandomDev26** [comment]
Yes, by description I meant the summary. I agree we should make it propose and then it can show up in a channel that we can name something like `gep-proposals`, and then leave the make/edit commands to the council and/or lords.

**Comment by gustavwilliam** [comment]
Hmmm, true. The issue with a command to create the GEPs on the server is that they can be above 2,000 characters, which Discord won't allow us to send.

Either way, we want to store the GEPs primarily on the site. We could communicate with Reagurk through the API when adding/proposing GEPs as well, and fetch data from there. Exactly how that would be done is something I haven't put any thought into.

Feel free to come with ideas.

**Comment by RandomDev26** [comment]
I was think it would be something like: draft (maybe split across multiple messages) on discord, and once it's ready, a PR is made on the GEP repo(would need to be made), and then the site would get the GEP from there.

**Comment by gustavwilliam** [comment]
Honestly, we don't really use GEPs anymore. Let's not do this unless we decide to go down that path.

Also, I don't think a GEP channel is really necessary. Let's just manage it from the site.
