### ISSUE TITLE
Increase ot-names update rate

### ISSUE THREAD

**Issue by gustavwilliam** [gurkult/gurkbot#126]
Update the active ot-name very 12 hours, instead of every 24 hours.

This means we'll get new names quicker, instead of having to wait a full day for a new name. If we get a repeated name, this will hopefully make things less boring. Aka more fun.

**Comment by onerandomusername** [comment]
gonna try to implement this

**Comment by onerandomusername** [comment]
Looking at the implementation, seems this will require some refactoring, but its doable.
