### ISSUE TITLE
Bot Status

### ISSUE THREAD

**Issue by Arnav-2004** [gurkult/gurkbot#132]
This will include !ping and !stats

`!ping`
![image](https://user-images.githubusercontent.com/70969910/123087428-27776c00-d442-11eb-8300-b8eb185a126a.png)

`!stats`
![image](https://user-images.githubusercontent.com/70969910/123087287-00b93580-d442-11eb-9e90-a8959ed7b24b.png)

- [ ] Anyone can implement this feature.
- [x] I would like to implement this feature myself.

**Comment by RohanJnr** [comment]
Looks good, go for it.
