### ISSUE TITLE
Bot core 

### ISSUE THREAD

**Issue by Vyvy-vi** [gurkult/gurkbot#17]
### Description:

#16 introduced a folder structure for the project. Contributors could start contributing if the discord bot-core is setup and a basic bot is running. 

Task-list: (suggested, if accepted)

~~`requirements.txt`~~
- [ ] new gh-branch for `develop`
- [ ] `.env-example` content for tokens etc. with how-to comments
- [ ] bot client setup
- [ ] setup constants, if any needed for now
- [ ] README.md with how to run
{ edit: }
- [ ] Pipfile
- [ ] Linting config  { see #18 }
- [ ] pre-commit hooks

**Comment by ReneganRonin** [comment]
Can we add Pipfile, Linting, and Pre-commit hooks to tasks?

**Comment by vivax3794** [comment]
We don't need a requirements.txt if we have a Pipfile

**Comment by zeeshanok** [comment]
> We don't need a requirements.txt if we have a Pipfile

What if we wanted to support both pipenv and regular pip?

**Comment by Vyvy-vi** [comment]
IMHO, keeping multiple ways to run code boosts inclusivity(since many new contributors might not be used to pipenv).
I think that's the reason why people started dockerizing their projects 🤔

**Comment by vivax3794** [comment]
> > We don't need a requirements.txt if we have a Pipfile
> 
> What if we wanted to support both pipenv and regular pip?

But that also adds extra work for developers that now need to update both

**Comment by gustavwilliam** [comment]
I’m not a big fan of letting people run the project in multiple ways. We should focus on documenting how it’s run, instead of trying to maintain multiple ways of running the project.

**Comment by ReneganRonin** [comment]
@gustavwilliam I actually agree on what @vivax3794 thought on this. Having it run multiple ways is a pain.

**Comment by vivax3794** [comment]
Also I would be happy to setup pipenv and write the core bot code (bot.py, __main__.py, and .env-example) and that should allow us to start adding commands/cogs

**Comment by Vyvy-vi** [comment]
(should I remove `requirements.txt` from task-list ?)

**Comment by gustavwilliam** [comment]
> @gustavwilliam I actually agree on what @vivax3794 thought on this. Having it run multiple ways is a pain.

Yes. That’s exactly what I’m saying as well. I think we’ve reached a consensus here.

**Comment by gustavwilliam** [comment]
@vivax3794 that sounds great. Would you like to open an issue about pipenv specifying what you’re gonna do? I’ll assign you.

**Comment by zeeshanok** [comment]
> > @gustavwilliam I actually agree on what @vivax3794 thought on this. Having it run multiple ways is a pain.
> 
> Yes. That’s exactly what I’m saying as well. I think we’ve reached a consensus here.

In that case, we should add some instructions on how to use pipenv.

**Comment by gustavwilliam** [comment]
Yes. That’s the plan, as I mentioned in one of my previous comments. Documenting everything and making it easy to set up is key.
