### ISSUE TITLE
Eval Command

### ISSUE THREAD

**Issue by ReneganRonin** [gurkult/gurkbot#24]
This is related to issue #13, specifically @gustavwilliam's [comment](https://github.com/gurkult/gurkbot/issues/13#issuecomment-749312590). @SuperMaZingCoder has made a cool [comment](https://github.com/gurkult/gurkbot/issues/13#issuecomment-749310909) as well, please check it out. This issue is where we will discuss things further for the eval command.

**Comment by Shivansh-007** [comment]
This would be done using [Tio Run](https://tio.run/#) , which supports more than 600 languages, and add the gurklang run command separetly.
Maybe like
```
!e js <code>
!e cpp <code>
!e py <code>
```
and for the gurklang it could be like
```
!gurklang <code>
```

**Comment by Shivansh-007** [comment]
I would be happy to work on the eval command.

**Comment by Shivansh-007** [comment]
we can close this now.

**Comment by gustavwilliam** [comment]
This has been completed. Thanks for the contribution.
