### ISSUE TITLE
Automatically give Gurkan role on name change

### ISSUE THREAD

**Issue by RandomDev26** [gurkult/gurkbot#32]
This feature would have the bot check a member's name every time it changes and if a variant of gurkan is in the name, it would give the gurkan role, else if it is not, it would remove the role. This would be done using the "on_member_update" function of discord.py.

**Comment by Shivansh-007** [comment]
What if a persons's discord username is gurkan?
And what if someone tries spamming, how about using tasks? We could run it every 1 hour or 30 minutes?

**Comment by RandomDev26** [comment]
> What if a persons's discord username is gurkan?

I'll also have it check on join

> And what if someone tries spamming, how about using tasks? We could run it every 1 hour or 30 minutes?

Yes, I agree

**Comment by gustavwilliam** [comment]
> And what if someone tries spamming, how about using tasks? We could run it every 1 hour or 30 minutes?
Only checking for this at certain time intervals doesn't sound too good UX-wise. I'd rather receive some minor spam from one odd person. They probably won't even consider this a feature to spam.

However, if we want to be on the safe side, I'm not against implementing some sort of warning for this. Let's say that a person changed their name 15 times in a minute. Then, I wouldn't mind potting that person on a cool down and saying "Hey, you've changed your name X times in Y minutes. Cool down," also possibly pinging the Steering Council.

We could also use a totally different model, where users only change their nicks through a `!nick` command. This would allow for flexibility with cool downs and similar, but I'm not a huge fan of restricting the user in this way. The UX of it isn't too nice imo.

At the end of the day, I don't think we'll be having an issue with this, so I wouldn't mind just ignoring it. But if we do want a warning of sorts, it would preferably be in a way similar to what I proposed above.

**Comment by RandomDev26** [comment]
I agree, I don't think anyone will think of spamming this feature. So would you like for me to add in a warning or not?

**Comment by gustavwilliam** [comment]
Not for now.

**Comment by Arnav-2004** [comment]
You need to fix one thing if not already done : It adds Gurkans role to the bots which have gurkan in their name like this one
![image](https://user-images.githubusercontent.com/70969910/103554948-b664ec00-4ed5-11eb-9de1-1f8749f19453.png)

**Comment by RandomDev26** [comment]
Added that in rn
