### ISSUE TITLE
New command proposition  by racingnbloxing 

### ISSUE THREAD

**Issue by ctrl-shift-make** [gurkult/gurkbot#37]
I have a new command proposition.
We discussed about this in the channel #dev-gurkbot. (27 December 2020)

It is to refer to any pull request on a Gurkult project.

Command  = !pr [project name]

This is a universal server command

I hope you are satisfied with my proposal.

**Comment by gustavwilliam** [comment]
This is already proposed in #11. Pull requests on GitHub are issues. We also discussed the best ways to implement #11 over on the server, but if you want to, feel free to continue the discussion in that issue instead.

I'm closing this, since it's a duplicate.
