### ISSUE TITLE
Add allowed mentions to make sure no @everyone/@role pings happen

### ISSUE THREAD

**Issue by ChiliMX** [gurkult/gurkbot#39]
Even though most commands that require user input are put into an embed, we still should include allowed mentions just to be safe. We don't want a pydis 2.0 to happen.

**Comment by gustavwilliam** [comment]
Sure. That's probably a good idea.

Would anyone be interested in implementing this?

**Comment by Inheritanc-e** [comment]
Yes sure, but for this we would also need logs category, to send notification to certain roles that this event was triggered.

**Comment by gustavwilliam** [comment]
Do we really need that?

**Comment by Inheritanc-e** [comment]
Better safe than sorry

**Comment by onerandomusername** [comment]
Have implemented
