### ISSUE TITLE
Who is working on what?

### ISSUE THREAD

**Issue by Arnav-2004** [gurkult/gurkbot#43]
So I was think what should I implement but I am confused. We should have an organized way to keep check on what is being worked on and who is working on it and what is left to implement.

**Comment by zeeshanok** [comment]
Isn't that what Assignees are?

**Comment by Arnav-2004** [comment]
> Isn't that what Assignees are?

Yes but it is hard to keep track.

**Comment by gustavwilliam** [comment]
We are planning on implementing an `.issue list` command. Maybe we could show the assignees in some way as well.

**Comment by gustavwilliam** [comment]
I'm currently sorting through the issues and adding the new labels. This should also help.
