### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by ReneganRonin** [gurkult/gurkbot#48]
A pagination feature can help make our bot's messages and embeds look very cool and tidy. Page for page baby!!!. Anyway, anyone want to implement this feature, I will assign u? I will be busy tomorrow so I won't do it.

**Comment by Vyvy-vi** [comment]
Having a default pagination interface would make menus easier to make :+1:
I could work on this.. 
Though I haven't worked with pagination a lot, so might have a few issues

**Comment by gustavwilliam** [comment]
Excellent. Personally, I think a menu row of reactions for navigation would be best if we had different versions of it. The buttons would navigate the embed pagination or delete the embed. There are three main types of navigation that I think we should have — the following:

If the embed is 4+ pages:
⏪ ◀️ ▶️ ⏩ 🗑️

If the embed is 2 or 3 pages:
◀️ ▶️ 🗑️

If the embed is 1 page:
🗑️

The last one is a simple 🗑️ that we could also use to let the user remove a bot embed. I think all three should be different pagination types that can be used separately, with an "dynamic" paginator that could be used if we want the bot to dynamically scale the amount of emojis (this one would simply apply the appropriate paginator).

Any thoughts on this? Would you like to implement something like this? You could get some inspiration and possibly migrate (parts of) the code for the PyDis paginates, if you want to.

**Comment by Vyvy-vi** [comment]
I would checkout PyDis' paginator, when I get time :+1:

**Comment by Shivansh-007** [comment]
This can be closes, implemented in #114
