### ISSUE TITLE
swear word checker

### ISSUE THREAD

**Issue by YuvrajGeek** [gurkult/gurkbot#49]

**Comment by gustavwilliam** [comment]
This seems to be two features without any description. Could you split it into separate issues and describe clearly what the features would be about?

**Comment by YuvrajGeek** [comment]
> This seems to be two features without any description. Could you split it into separate issues and describe clearly what the features would be about?

The contributors command (coming straight from the GitHub API):
![image](https://user-images.githubusercontent.com/63858962/103408016-cc497880-4b86-11eb-8226-4da871c9e971.png)

For the toxicity checker, I thought of two ways:
- Listing out all the toxic words in a list and checking their presence in a message.
- Using NLTK for contextual detection of toxicity (I don't have any idea as of now for this). I had read an overview for this here: https://arxiv.org/ftp/arxiv/papers/1903/1903.06765.pdf

Contextual Detection of toxicity would help more since we are actually detecting hate speech rather than just checking the presence of swear words which maybe used in a lighter sense. A good example of this is: https://github.com/conversationai/perspectiveapi/

**Comment by Vyvy-vi** [comment]
with regard to NLTK:
- How much performance demanding would the program be?
- Is the execution time fast?

Moreover, could we consider libraries that do the same, such as python equivalents of alex.js and retext-equality?

**Comment by Shivansh-007** [comment]
Yeah just what Vyvy said and why not just use google bad words list, like [here](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badwordslist/badwords.txt)

**Comment by Inheritanc-e** [comment]
I think swearing would be fine if they don't do it too excessively, we can blacklist some words that would alert a role saying that a person has said a blacklisted word.
This would probably be enough.

**Comment by Shivansh-007** [comment]
We can do the alert roles, if the person uses it repeatedly, like 2..3 times in 10 seconds or something.

**Comment by Vyvy-vi** [comment]
personally, I find nltk models to be rather dull
This is an example of a similar blocking we use in another place(this uses a highly trained library... but still a long way to go)
![Screenshot 2020-12-31 at 5 39 05 PM](https://user-images.githubusercontent.com/62864373/103409978-37974880-4b8f-11eb-8945-0f683b2fd356.png)

**Comment by YuvrajGeek** [comment]
> with regard to NLTK:
> 
> * How much performance demanding would the program be?
> * Is the execution time fast?
> 
> Moreover, could we consider libraries that do the same, such as python equivalents of alex.js and retext-equality?
> 
> Also, in my opinion: keeping issues and PRs centric on similar agendas helps maintainers manage them much more easily

In that case, we should use the first of the two methods that i gave cuz that would be comparitively more performance efficient.
And yeah, I edited the issue title cuz i have made another one

**Comment by gustavwilliam** [comment]
We would presumably have a filter on the bot, that alerts mods and/or deletes the messages that include things we absolutely don't want to have on the server. This could be nazist and rasist symbols and words, that mods should be on the lookout for.

However, I don't want some feature that penalises the users for swearing. The toxisity checker also seems like a nightmare to implement, if it can even be done. Let's have an issue about implementing a filter instead.

**Comment by YuvrajGeek** [comment]
> We would presumably have a filter on the bot, that alerts mods and/or deletes the messages that include things we absolutely don't want to have on the server. This could be nazist and rasist symbols and words, that mods should be on the lookout for.
> 
> However, I don't want some feature that penalises the users for swearing. The toxisity checker also seems like a nightmare to implement, if it can even be done. Let's have an issue about implementing a filter instead.

Yeah, you are absolutely right. I agree that we should have a filter checker rather than an absolute "toxicity" checker.
