### ISSUE TITLE
Commands to search GitHub users and repos

### ISSUE THREAD

**Issue by YuvrajGeek** [gurkult/gurkbot#51]
i am thinking of making it like this:

`.gitsearch users YuvrajGeek`
this would send an embed with the top 8-10 search results and if the search results are less than 3, then it will send an embed of the first search result because GitHub ranks user search results on the basis of their activity so first result will always be a reliable one.

`.gitsearch repos gurkbot`
this would send an embed the same way the users search works

If required, this can be further extended to searching sites like Instagram as a part of `fun` commands.
I am willing to add the above `GitHub` commands and if approved, i shall add the Instagram command as well.

**Comment by Vyvy-vi** [comment]
I think there's already an issue for this in #11 and someone is working on that.
Maybe you could send a message there, so that you could team up on this?

**Comment by Shivansh-007** [comment]
Well I dunno if there is a need of them, we could always go to GitHub and search tho.

**Comment by YuvrajGeek** [comment]
> I think there's already an issue for this in #11 and someone is working on that.
> Maybe you could send a message there, so that you could team up on this?

That issue is for this repo only ig, mine is globally for entire GitHub

**Comment by Shivansh-007** [comment]
> > I think there's already an issue for this in #11 and someone is working on that.
> > Maybe you could send a message there, so that you could team up on this?
> 
> That issue is for this repo only ig, mine is globally for entire GitHub

No no, it is for full GitHub, but the Gurkult is the primary default (according to channels).

**Comment by Vyvy-vi** [comment]
> That issue is for this repo only ig, mine is globally for entire GitHub

I think it's been implemented for full github already

**Comment by gustavwilliam** [comment]
Would this be a general search command, so things like users and repos would both pop up, or would it consist of two subcommands? We already have something for finding exact users and possibly repos in #11, so I'm not sure what purpose this would serve. If someone is looking to browse GitHub users, why not just go onto GitHub.com?

In short, I'm asking these two things:
- Would this be useful?
- How would it interact with #11 and the general `!github` command?

**Comment by YuvrajGeek** [comment]
> Would this be a general search command, so things like users and repos would both pop up, or would it consist of two subcommands? We already have something for finding exact users and possibly repos in #11, so I'm not sure what purpose this would serve. If someone is looking to browse GitHub users, why not just go onto GitHub.com?
> 
> In short, I'm asking these two things:
> 
> * Would this be useful?
> * How would it interact with #11 and the general `!github` command?

## Question 1:
I have seen in some programming servers that the chat talks about something of GitHub and its not able to reach to an explicit point. This is not a "must have" command (that gets the high priority badge) but it makes a programming server look more in the niche. And, if demanded, I can add special priviliges to the results of Gurkult and its repositories but I think this is what is being done on [#11](https://github.com/gurkult/gurkbot/issues/11)

## Question 2:
As mentioned [here](https://github.com/gurkult/gurkbot/issues/11#issue-771281663), the command "allows users to retrieve issues from all github repos of **gurkult**." while this issue/feature (#51) is about searching users and repositories all over GitHub.

**Comment by gustavwilliam** [comment]
I don't quite see what you're referring to in how it would be useful. Would we look more "in niche" by letting users fuzzy search repos, instead of searching with for an exact one, on the bot? That doesn't quite make sense.

Issue #11 is referring to having gurkult as the default, but still letting the user specify any repo from any organisation and user.

**Comment by YuvrajGeek** [comment]
> I don't quite see what you're referring to in how it would be useful. Would we look more "in niche" by letting users fuzzy search repos, instead of searching with for an exact one, on the bot? That doesn't quite make sense.
> 
> Issue #11 is referring to having gurkult as the default, but still letting the user specify any repo from any organisation and user.

Okay, I get your point. Closing this issue now. But I have written some code, see if it can be utilised for #11 .
