### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by ReneganRonin** [gurkult/gurkbot#7]
# My Idea is too complex...
Based on @gustavwilliam 's suggestion, my idea is rather complex since the bot is still at its infancy. So here is the updated workflow according to @gustavwilliam :
### Steps
1. Evaluate what features we want
2. Create bot core and fix dependency management and similar
3. Implement features

### Comments on workflow:
1. I agree on the workflow.
2. I suggest we create two branches - `core` and `develop`:
  - `core` branch _is_ the bot's core so if anything is messed up, it stays there.
  - `develop` is where we test the new features. We create this features by branching off from the `develop` branch. The branches should be named after the feature (e.g. `feature/ci`) and then PR to develop for further testing. These will prevent mishaps if something goes wrong from the feature branch.
3. Alrighty! Let's go!!!

Feel free to comment here and discuss.

**Comment by Vyvy-vi** [comment]
That would be good 👍 
Also, since this issue is titled Workflows, perhaps we could make a few actions to Lint and Build, to ensure code quality from prs?

**Comment by ReneganRonin** [comment]
I guess this is not needed. https://github.com/gurkult/gurkbot/pull/20 <- done that
