### ISSUE TITLE
`isgurkan` command works for any input.

### ISSUE THREAD

**Issue by SuperMaZingCoder** [gurkult/gurkbot#70]
The `!isgurkan` command is currently accepting any input, regardless of whether it is an actual user or not. Here is an example:

![image](https://user-images.githubusercontent.com/55718659/104129662-f0514a80-533a-11eb-8f4f-dc71dd3c8fa2.png)

I think we should add some checks to ensure that the input is a *mention* or *user ID*. What do you all think?

**Comment by Inheritanc-e** [comment]
We should just specify the parameter to be `discord.Member`, because 

1. Not everyone has developer mode turned on.
2. People don't when they are pinged for no reason.

**Comment by gustavwilliam** [comment]
I personally don't mind checking strings. For example, something like this should be valid imo:
<img width="294" alt="Screenshot 2021-01-10 at 18 12 36" src="https://user-images.githubusercontent.com/65498475/104130133-6c658580-536f-11eb-937c-0c8418b570d3.png">

**Comment by gustavwilliam** [comment]
I'm closing this, unless we have something more to add.
