### ISSUE TITLE
Eval command bug

### ISSUE THREAD

**Issue by Arnav-2004** [gurkult/gurkbot#74]
When you do
!e py
```
a
```
Here the language is specified outside the code block
It gives error: https://discord.com/channels/789192517375623228/793570459945926717/800007399778811954

but when you do
!e
```py
a
```
Here the language is specified inside the code block
It does not give error: https://discord.com/channels/789192517375623228/793570459945926717/800007441349345281

**Comment by Shivansh-007** [comment]
Hmmm, do you know what is causing this issue?
