### ISSUE TITLE
Use custom status embeds for workflow runs

### ISSUE THREAD

**Issue by Shivansh-007** [gurkult/gurkbot#78]
This will introduces custom status embeds for our workflow runs. The standard embeds GitHub sends to our webhook do not contain a lot of information and, because they're being sent for every individual workflow, generate a lot of noise in our `#dev-log` channel. By using a custom action to send embeds, we can fine tune when we want to send out an embed.

### Examples
**Pull Request Embed**

![image](https://user-images.githubusercontent.com/69356296/104924804-f3e07380-59c3-11eb-9e2b-98d9282ac4b2.png)

**General Workflow Embed**

![image](https://user-images.githubusercontent.com/69356296/104924817-f80c9100-59c3-11eb-8dac-1b7d99895911.png)

**Comment by onerandomusername** [comment]
Implemented by 9f25757892f342ee9f6ecf57e53d318f92653a71

**Comment by onerandomusername** [comment]
Closed by #145
