### ISSUE TITLE
Changing off-topic prefix

### ISSUE THREAD

**Issue by RohanJnr** [gurkult/gurkbot#92]
## Abstract
Change off-topic channel prefix every day.

## Implementation
Store off-topic names in a JSON file.
```
{
the user who appended the name: name
}
```

## What off-topic names?
Off-topic names should be added via a command.
This command would be only used by mods+ (Idk what roles should be able to use it).

**Comment by gustavwilliam** [comment]
Nice idea! A few thoughts:
- Lord gurkans+ should be able to use it imo, or contrib+
- If we're storing the name of the user who added it, why not store more data? We can store the message ID that added it, the time it was added, last used and who added it. This will allow us to make links to just to message and display some nice meta-data about it.

 For the way we store the names (assuming we use json?), it would make sense to use something like the following (pseudocode):
```json
{
	index: {
		"name": str,
		”date_added": datetime,
		"add_message": message_id,
		"added_by": user_id,
		"last_used": date
	}
}
```

What do you think? Maybe we should alter, remove or add something? The exact names are just placeholders right now, but something like that should work.

**Comment by RohanJnr** [comment]
looks good, I was wondering if we wanted to store this in a database instead of JSON incase there is a plan on getting a DB

**Comment by codephile1221** [comment]
Database all the way baby.
