### ISSUE TITLE
Setup Postgres database

### ISSUE THREAD

**Issue by gustavwilliam** [gurkult/gurkbot#93]
We need a database for the bot and the plan is to use Postgres.

**Comment by RohanJnr** [comment]
We can use asyncpg/sqlalchemy_aio for connecting to the database with the bot.
Also, a docker-compose file to run the bot and the database in 2 containers.
#92 can be the first feature that can use this database.

**Comment by gustavwilliam** [comment]
Sure thing! I haven't used that database manager, but I'll trust your judgement on that one, unless someone else has something to add.
