### ISSUE TITLE
New Command Suggestion: !bonk

### ISSUE THREAD

**Issue by ShakyaMajumdar** [gurkult/gurkbot#96]
When invoked, will send a gif of the user mentioned being bonked.

Example:
!bonk @hahastinkypoop

![out](https://user-images.githubusercontent.com/69471777/110197135-7daea800-7e6f-11eb-9612-ca2f23d6810b.gif)

**Comment by v1nam** [comment]
is this just inserting the resized pfp in the image array of the gif, and inserting a more resized pfp at the bonking frame?

**Comment by ShakyaMajumdar** [comment]
Yeah

**Comment by v1nam** [comment]
nice then

**Comment by ShakyaMajumdar** [comment]
Should I start working on incorporating it into the bot?

**Comment by v1nam** [comment]
yah should be good, though can you make the bg transparent :thinking:

**Comment by ShakyaMajumdar** [comment]
Tried it, didn't quite work out:
![image](https://cdn.discordapp.com/attachments/789198156218892358/817631301481529364/out.gif)

**Comment by v1nam** [comment]
welp

**Comment by v1nam** [comment]
What are you doing to make it transparent? wouldn't it be better to make the template transparent from a designing editor or something beforehand?

**Comment by ShakyaMajumdar** [comment]
> What are you doing to make it transparent?

Searches on stackoverflow, lol

> wouldn't it be better to make the template transparent from a designing editor or something beforehand?

the original gif is already transparent, it gets messed up only when I paste another image on it.

**Comment by v1nam** [comment]
That's probably because you are opening it in RGB mode

**Comment by v1nam** [comment]
Did you try doing it with `RGBA`?

**Comment by v1nam** [comment]
Or would be easier if I can look at the code

**Comment by ShakyaMajumdar** [comment]
code:
https://gist.github.com/ShakyaMajumdar/2eeabfadd4536c7291f1b322f31313fa

**Comment by gustavwilliam** [comment]
Hi, this is a nice command. Two things:
- I dislike that particular gif. Could you use some other one?
- Let’s put the avatar in a circle (like it is on Discord)

mother than that, great work!

**Comment by ShakyaMajumdar** [comment]
> I dislike that particular gif. Could you use some other one?
Sure, I'll search for some more, am also open to suggestions from others.

>Let’s put the avatar in a circle (like it is on Discord)
Think that shouldn't be too hard

> Other than that, great work!
Thanks!

**Comment by codephile1221** [comment]
Hello @ShakyaMajumdar , it is I, Yoda- Jedi Master and Grand Master of the Jedi High Council.

Feel free to open a draft PR if you are just working out ideas.

**Comment by gustavwilliam** [comment]
This has been merged. Thanks for implementing and reviewing it!
